// <auto-generated />
namespace QuanLiDangKiC_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class rebui : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rebui));
        
        string IMigrationMetadata.Id
        {
            get { return "202504151420445_rebui"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
